### birinchi navbatda kutubxonani yuklash bilan boshlaymiz hozir menda avvol bu kutubxona o'rnatilgani uchun xatolik chiqaryapti

In [1]:
!pip install opencv-python

You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install numpy

You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
#endi bizga kerak kutubxonalardi chaqirib olamiz
import cv2
import numpy as np

In [9]:
#ishni eng avval rasm yaratishdan boshlaymiz
rasm = np.full((200,200,3),255, dtype='uint8')#numpydan foydalanib
#3d array hosil qildik va uning o'lchamini 200ga 2000 qilib ichini oqga bo'yadik va sonlarning typeni uint8 qildik
cv2.imshow("Dars",rasm)#rasmni chiqarib unga nom berdik
cv2.waitKey(0)#bu yerda rasmni qancha vaqt ushlab turish
cv2.destroyAllWindows()
#bu kodni ishga tushirgandan keyin kampyuter panelida python ikonkasi chiqib turubdi shuni ochib ko'ring

In [10]:
#rasmning ma'lumotlarini ekranga chiqarish ko'ramiz
print(rasm)
print(rasm.shape)
print(rasm.ndim)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(200, 200, 3)
3


# Oq-qora rasm

In [15]:
#bu rasm 2ta kanaldan iborat shuning uchun oq-qora rasm hosil boladi
rasm = np.random.randint(0,255,size=(300,300),dtype='uint8')
cv2.imshow("Oqqora",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
rasm.shape

(300, 300)

In [14]:
rasm.ndim

2

# RGB yoki Rangli rasm

In [16]:
rasm = np.random.randint(0,255,size=(300,300,3),dtype='uint8')
cv2.imshow("RGB",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Rasmlar bilan ishlash

In [17]:
rasm_1 = np.random.randint(0,120,size=(300,300,3),dtype="uint8")
rasm_2 = np.random.randint(120,240,size=(300,300,3),dtype=np.uint8)

In [21]:
#1-rasmni ekranga chiqarib ko'ramiz
cv2.imshow("Rasm1",rasm_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
#2-rasmni ekranga chiqarib ko'ramiz
cv2.imshow("Rasm2",rasm_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
#wta rasmni birlashtirib ekranga chiqarib ko'ramiz
rasm_3 = np.hstack((rasm_1,rasm_2))
cv2.imshow("Rasm3",rasm_3)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Rasmni o'qib olish

In [27]:
a = cv2.imread("rasmlar/Tashkent.png")#Alohida rasmlar degan papka 
#ochib olamiz va u yerga bitta rasm joylaymiz shuni biz kodimizda o'qib olamiz

In [28]:
print(a)#e'tibor berib turganingizdek rasmlar oddiy sonlardan tashkil topgan

[[[140  21   0]
  [140  21   0]
  [140  21   0]
  ...
  [184  34   0]
  [184  34   0]
  [184  34   0]]

 [[140  21   0]
  [140  21   0]
  [141  22   0]
  ...
  [184  34   0]
  [184  34   0]
  [184  34   0]]

 [[140  21   0]
  [141  22   0]
  [141  22   0]
  ...
  [185  35   0]
  [185  35   0]
  [185  35   0]]

 ...

 [[ 26  56  37]
  [ 26  56  37]
  [ 25  57  38]
  ...
  [133 112 110]
  [134 113 111]
  [136 115 113]]

 [[ 20  57  37]
  [ 20  57  37]
  [ 20  59  38]
  ...
  [111  92  85]
  [113  94  87]
  [115  96  89]]

 [[ 20  57  37]
  [ 20  57  37]
  [ 20  59  38]
  ...
  [117  98  91]
  [119 100  93]
  [121 102  95]]]


In [31]:
rasm = cv2.imread("rasmlar/Tashkent.png")
cv2.imshow("Rasm",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
rasm.shape#o'lchhamlari

(275, 183)

# Oq qora o'qish

In [34]:
rasm = cv2.imread("rasmlar/Tashkent.png",0)
cv2.imshow("Rasm",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Rasmni burish

In [37]:
rasm = cv2.imread("rasmlar/Tashkent.png")
cv2.imshow("Rasm",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
rasm_2 = np.rot90(rasm,5)#rasmni burish uchun rot90 funksiyasidan foydalandik
cv2.imshow("Rasm",rasm_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Rasmdi normallashtirish

In [40]:
rasm = cv2.imread("rasmlar/Tashkent.png")
cv2.imshow("Rasm",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
print(rasm)

[[[140  21   0]
  [140  21   0]
  [140  21   0]
  ...
  [184  34   0]
  [184  34   0]
  [184  34   0]]

 [[140  21   0]
  [140  21   0]
  [141  22   0]
  ...
  [184  34   0]
  [184  34   0]
  [184  34   0]]

 [[140  21   0]
  [141  22   0]
  [141  22   0]
  ...
  [185  35   0]
  [185  35   0]
  [185  35   0]]

 ...

 [[ 26  56  37]
  [ 26  56  37]
  [ 25  57  38]
  ...
  [133 112 110]
  [134 113 111]
  [136 115 113]]

 [[ 20  57  37]
  [ 20  57  37]
  [ 20  59  38]
  ...
  [111  92  85]
  [113  94  87]
  [115  96  89]]

 [[ 20  57  37]
  [ 20  57  37]
  [ 20  59  38]
  ...
  [117  98  91]
  [119 100  93]
  [121 102  95]]]


In [44]:
rasm = cv2.imread("rasmlar/Tashkent.png")
#bu yerda biz rasmning typeni float32ga o'tkazib 255ga bolib yubordik
rasm_2 = rasm.astype("float32") / 255.0
#avval rasmni hosil qilib turgan sonlar 0va255 sonlar orasida bolgan bolsa endi 0va1 orasida boladi
cv2.imshow("Rasm",rasm_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
print(rasm_2)

[[[0.54901963 0.08235294 0.        ]
  [0.54901963 0.08235294 0.        ]
  [0.54901963 0.08235294 0.        ]
  ...
  [0.72156864 0.13333334 0.        ]
  [0.72156864 0.13333334 0.        ]
  [0.72156864 0.13333334 0.        ]]

 [[0.54901963 0.08235294 0.        ]
  [0.54901963 0.08235294 0.        ]
  [0.5529412  0.08627451 0.        ]
  ...
  [0.72156864 0.13333334 0.        ]
  [0.72156864 0.13333334 0.        ]
  [0.72156864 0.13333334 0.        ]]

 [[0.54901963 0.08235294 0.        ]
  [0.5529412  0.08627451 0.        ]
  [0.5529412  0.08627451 0.        ]
  ...
  [0.7254902  0.13725491 0.        ]
  [0.7254902  0.13725491 0.        ]
  [0.7254902  0.13725491 0.        ]]

 ...

 [[0.10196079 0.21960784 0.14509805]
  [0.10196079 0.21960784 0.14509805]
  [0.09803922 0.22352941 0.14901961]
  ...
  [0.52156866 0.4392157  0.43137255]
  [0.5254902  0.44313726 0.43529412]
  [0.53333336 0.4509804  0.44313726]]

 [[0.07843138 0.22352941 0.14509805]
  [0.07843138 0.22352941 0.14509805]


In [46]:
print(rasm_2.dtype)

float32


In [49]:
rasm_3 = np.around(rasm_2,1)#round funksiyasidan foydalanib sonlarni yaxlitlab oladik, ammo rasm ham ozgina hiralashganiga e'tibor bearisiz 
print(rasm_3)

[[[0.5 0.1 0. ]
  [0.5 0.1 0. ]
  [0.5 0.1 0. ]
  ...
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]]

 [[0.5 0.1 0. ]
  [0.5 0.1 0. ]
  [0.6 0.1 0. ]
  ...
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]]

 [[0.5 0.1 0. ]
  [0.6 0.1 0. ]
  [0.6 0.1 0. ]
  ...
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]
  [0.7 0.1 0. ]]

 ...

 [[0.1 0.2 0.1]
  [0.1 0.2 0.1]
  [0.1 0.2 0.1]
  ...
  [0.5 0.4 0.4]
  [0.5 0.4 0.4]
  [0.5 0.5 0.4]]

 [[0.1 0.2 0.1]
  [0.1 0.2 0.1]
  [0.1 0.2 0.1]
  ...
  [0.4 0.4 0.3]
  [0.4 0.4 0.3]
  [0.5 0.4 0.3]]

 [[0.1 0.2 0.1]
  [0.1 0.2 0.1]
  [0.1 0.2 0.1]
  ...
  [0.5 0.4 0.4]
  [0.5 0.4 0.4]
  [0.5 0.4 0.4]]]


In [48]:
cv2.imshow("Rasm",rasm_3)
cv2.waitKey(0)
cv2.destroyAllWindows()

# rasm kanallari

In [51]:
rasm = cv2.imread("rasmlar/Tashkent.png")
cv2.imshow("Rasm",rasm)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
blue_canal = rasm[:,:,0]
green_canal = rasm[:,:,1]
red_canal = rasm[:,:,2]

In [53]:
red_canal

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [ 37,  37,  38, ..., 110, 111, 113],
       [ 37,  37,  38, ...,  85,  87,  89],
       [ 37,  37,  38, ...,  91,  93,  95]], dtype=uint8)

In [54]:
green_canal

array([[ 21,  21,  21, ...,  34,  34,  34],
       [ 21,  21,  22, ...,  34,  34,  34],
       [ 21,  22,  22, ...,  35,  35,  35],
       ...,
       [ 56,  56,  57, ..., 112, 113, 115],
       [ 57,  57,  59, ...,  92,  94,  96],
       [ 57,  57,  59, ...,  98, 100, 102]], dtype=uint8)

In [55]:
blue_canal

array([[140, 140, 140, ..., 184, 184, 184],
       [140, 140, 141, ..., 184, 184, 184],
       [140, 141, 141, ..., 185, 185, 185],
       ...,
       [ 26,  26,  25, ..., 133, 134, 136],
       [ 20,  20,  20, ..., 111, 113, 115],
       [ 20,  20,  20, ..., 117, 119, 121]], dtype=uint8)

In [58]:
print(rasm[0,0,0])
print(rasm[0,0,1])
print(rasm[0,0,2])

140
21
0


In [59]:
rasm

array([[[140,  21,   0],
        [140,  21,   0],
        [140,  21,   0],
        ...,
        [184,  34,   0],
        [184,  34,   0],
        [184,  34,   0]],

       [[140,  21,   0],
        [140,  21,   0],
        [141,  22,   0],
        ...,
        [184,  34,   0],
        [184,  34,   0],
        [184,  34,   0]],

       [[140,  21,   0],
        [141,  22,   0],
        [141,  22,   0],
        ...,
        [185,  35,   0],
        [185,  35,   0],
        [185,  35,   0]],

       ...,

       [[ 26,  56,  37],
        [ 26,  56,  37],
        [ 25,  57,  38],
        ...,
        [133, 112, 110],
        [134, 113, 111],
        [136, 115, 113]],

       [[ 20,  57,  37],
        [ 20,  57,  37],
        [ 20,  59,  38],
        ...,
        [111,  92,  85],
        [113,  94,  87],
        [115,  96,  89]],

       [[ 20,  57,  37],
        [ 20,  57,  37],
        [ 20,  59,  38],
        ...,
        [117,  98,  91],
        [119, 100,  93],
        [121, 102,  95]]

In [60]:
cv2.imshow("Blue",blue_canal)
cv2.waitKey(0)
cv2.destroyAllWindows()